# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeleteUserDataFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeleteUserDataFirebase
   pod 'FirebaseUI/Auth'
   pod 'FirebaseFirestore'
   pod 'FirebaseDatabase'
   pod 'FirebaseStorage'
   pod 'Alamofire'

end
